config/routes.rb
Rails.application.routes.draw do

  root :to => 'pages#home'
  get 'pages/:page_name' => 'pages#index', :as => :pages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def index
    @title = params[:page_name].titleize
    render params[:page_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <div class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </div>
  <% if ContactUs.require_subject %>
    <div class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </div>
  <div class='commit'>
    <%= f.submit :submit, :class => 'submit create', :title => t('.submit') %>
  </div>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
<% end %>

app/views/layouts/_blog_top_menu.html.haml
%ul#navigation.slimmenu
  %li
    =link_to "HOME", '/'
  %li
    =link_to "ABOUT", '/pages/about'
  %li
    %a{:href => ""} THE CAUSES
  %li
    =link_to "VIDEOS", '/pages/about'
  %li
    %a{:href => ""} CONTACT

app/views/layouts/_top_menu.html.haml
%ul#navigation.slimmenu
  %li
    =link_to "HOME", root_path
  %li
    =link_to "ABOUT", pages_path("about")
  %li
    %a{:href => ""} THE CAUSES
  %li
    =link_to "VIDEOS", pages_path("videos")
  %li
    %a{:href => ""} CONTACT

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cdg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
/[if IEMobile 7 ] <html class="no-js iem7">
/ [if (gt IEMobile 7)|!(IEMobile)]><!
%html.no-js
  / <![endif]
  %head
    %link{:rel => 'shortcut icon', :href => '/assets/favicon.ico' }
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{:rel => 'stylesheet', :href => 'http://fonts.googleapis.com/css?family=Open+Sans', :type => 'text/css'}
    %link{:href => "http://fonts.googleapis.com/css?family=Lato:300,400", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}/
  %body
    %div.container
      = render :partial => "layouts/top_menu"
      .box
        = yield

app/views/layouts/blog.html.haml
!!!
/[if IEMobile 7 ] <html class="no-js iem7">
/ [if (gt IEMobile 7)|!(IEMobile)]><!
%html.no-js
  / <![endif]
  %head
    %link{:rel => 'shortcut icon', :href => '/assets/favicon.ico' }
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %link{:rel => 'stylesheet', :href => 'http://fonts.googleapis.com/css?family=Open+Sans', :type => 'text/css'}
    %link{:href => "http://fonts.googleapis.com/css?family=Lato:300,400", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css", :rel => "stylesheet"}/
  %body
    %div.container
      = render :partial => "layouts/blog_top_menu"
    #image
      = image_tag('header.png', :class => 'centered-header')
    #content
      =yield

app/views/pages/about.html.haml
#main
  %p The goal of this endeavor is to harness the energy I put into dancing and somehow convert it into a force for good in this world, specifically in relation to climate change, social justice and gender equality.  Most likely, I will fail, but it’s not going to hurt to try.  Read on for brief summaries of the what, why and how of this venture.
  %h3 What
  %p I’ve been called “crazy dancing guy” by a lot of people over the years.  When I go out dancing, people seem to enjoy watching me dance, and often record me doing so.  So this venture is me totally embracing the “CrazyDancingGuy” persona and seeing what I can do with it.  Perhaps, by some miracle, my dancing can earn me a megaphone to speak out for the things I care about or earn me money to support these important causes.
  %h3 Why
  %p Dancing is my primary hobby; I might even call it an obsession.  I spend an average of 7 or more hours a week dancing, and would surely do it even more often if I lived somewhere with a more steady flow of good music.  Meanwhile, most of the rest of my time is spent working for a better world, and for a long time, I’ve felt guilty taking breaks from those efforts to go out dancing.  With @CrazyDancingGuy, I hope I can do both at the same time.
  %p For specifics on why we need to be fighting for climate justice, social justice or gender equality, visit their corresponding pages.
  %h3 How
  %p Yeah, this is the tricky part.  My probably-delusional plan consists of three main parts:
  %ul
    %li wearing my crazydancingguy gear anytime I'm out dancing, while encouraging people to film and share my dance moves to raise awareness about The Causes
    %li producing weekly videos capturing my crazy dancing in various creative ways and using these to build a popular YouTube channel
    %li networking with organizations connected to the causes to help promote my message of spreading good through dance
  %p The general idea being that if I make any noise, or any money, I would be able to leverage those assets to support work on The Causes.  While very difficult to stand out amongst all the noise on the web, there are numerous instances of people generating considerable revenue from successful YouTube channels, and in general, unique dancing videos make for highly shareable content.

app/views/pages/home.html.haml
#main
  #image
    = image_tag('header.png', :class => 'centered-header')
  #content
    #desc
      %h2 Hi, I'm @CrazyDancingGuy
      %p I love to dance, and so I do it a lot.  Often, when I'm out dancing, people watch or even record my antics.
      %p The other day I thought, "if I am going to spend hours every week with people watching me dance, I might as well seize that opportunity to speak up for the things I care about."
      %p So I created the CrazyDancingGuy persona.  Now when I go out dancing, I will wear a shirt in support of climate justice, gender equality and social justice.
      %p My shirt will also encourage onlookers to share dancing videos / pics and tag the causes they care about.
      %p It's a crazy idea.  It may not work at all.  But I'm going have fun trying.  Why not?
      %h2 #crazydancingguy

app/views/pages/videos.html.haml
#main
  #image
    = image_tag('header.png', :class => 'centered-header')
  #content
    %h3 Videos
    %p click on any to play
    %ul.youtube-video-gallery{:style=>"padding-left: 15px;"}